#!/usr/bin/env php
<?php
include dirname(__FILE__) . '/app/bootstrap.php';
include dirname(__FILE__) . '/app/middleware.php';


$app = $container->get('console');

// to execute, use: php events <CommandName>
// from the CLI
$app->run();